### PR TITLE
make a the comment preview style different enough that it doesn't look editable

### PR DESCRIPTION
**Pull request by mixmix**
I'm not sure the best way to test this. I'm perhaps 70% confident I've hit the right style :P

### CODE REVIEW

**Comment by pfraze** [comment]
Did you mean to set the opacity to 0?

**Comment by mixmix** [comment]
Herp derp, should have been 0.5
Will fix when back at computer

**Comment by mixmix** [comment]
fixed ! @pfraze

**Comment by pfraze** [comment]
:+1: I dig it. Thanks!

**Comment by pfraze** [comment]
publied `ssb-patchwork-ui@0.0.20`

**Pull request merged**
